---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /home/semaphore/vars/vcenter.yml
  tasks:
    - name: List vms
      community.vmware.vmware_vm_info:
        validate_certs: no
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
      delegate_to: localhost
      register: vminfo

    - name: Write vminfo to a JSON file
      copy:
        content: "{{ vminfo | to_nice_json }}"
        dest: /home/semaphore/files/vcenter/list.json

