---
- name: Create individual files for VM info
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: /home/semaphore/bucket/Vcenter/Vms

    - name: Pause for 1 minutes to delete files
      ansible.builtin.pause:
        minutes: 1 

    - name: Read JSON file
      slurp:
        src: /home/semaphore/files/vcenter/list.json
      register: json_file_content

    - name: Parse JSON content
      set_fact:
        vm_info: "{{ json_file_content.content | b64decode | from_json }}"
  
    - name: Create files for VM info
      file:
        path: "/home/semaphore/bucket/Vcenter/Vms/{{ item.guest_name }}.md"
        state: touch
      loop: "{{ vm_info.virtual_machines }}"
      loop_control:
        loop_var: item

    - name: Populate files with VM info
      lineinfile:
        line: |
          IP Address: {{ item.ip_address }}
          ESXi Hostname: {{ item.esxi_hostname }}
          Guest Fullname: {{ item.guest_fullname }}
        path: "/home/semaphore/bucket/Vcenter/Vms/{{ item.guest_name }}.md"
      loop: "{{ vm_info.virtual_machines }}"
      loop_control:
        loop_var: item
