---
- hosts: all
  gather_facts: false
  become: true
  become_user: root

  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11
  tasks:
    - name: set domain_name
      set_fact: 
        domain_name: Wildcard.martinlaan.be

    - name: get certs
      fetch:
        src: "/conf/acme/{{ item }}"
        dest: /home/semaphore/certs/ 
        flat: yes
      with_items:
      - "{{ domain_name }}.fullchain" 
      - "{{ domain_name }}.ca"
      - "{{ domain_name }}.key"
      - "{{ domain_name }}.crt"